In [1]:
%cd /content/drive/MyDrive/FYP

/content/drive/MyDrive/FYP

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Demographics Data

In [3]:
demo_df = pd.read_csv('2024-Q3/DEMO24Q3.txt', sep='$')
demo_df

<ipython-input-3-ed8bd779cf36>:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  demo_df = pd.read_csv('2024-Q3/DEMO24Q3.txt', sep='$')

,primaryid,caseid,caseversion,i_f_code,event_dt,mfr_dt,init_fda_dt,fda_dt,rept_cod,auth_num,...,age_grp,sex,e_sub,wt,wt_cod,rept_dt,to_mfr,occp_cod,reporter_country,occr_country
0,100138392,10013839,2,F,NaN,20240716,20140316,20240726,EXP,NaN,...,NaN,M,Y,NaN,NaN,20240726,NaN,HP,FI,FI
1,1002310548,10023105,48,F,20140101.0,20240626,20140320,20240715,EXP,NaN,...,E,F,Y,NaN,NaN,20240715,NaN,MD,CA,CA
2,100313066,10031306,6,F,20130101.0,20240726,20140324,20240802,EXP,NaN,...,NaN,F,Y,53.0,KG,20240802,NaN,MD,JP,JP
3,100445154,10044515,4,F,NaN,20240429,20140328,20240922,EXP,NaN,...,NaN,F,Y,110.0,KG,20240922,NaN,HP,IT,IT
4,100635983,10063598,3,F,20140319.0,20240715,20140407,20240725,EXP,NaN,...,NaN,M,Y,89.0,KG,20240725,NaN,MD,GB,GB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405508,989327138,9893271,38,F,20130603.0,20240307,20140213,20240730,EXP,NaN,...,A,F,Y,74.0,KG,20240730,NaN,MD,CA,CA
405509,98974507,9897450,7,F,20120123.0,20231018,20140214,20240919,EXP,NaN,...,A,M,Y,72.0,KG,20240919,NaN,MD,ES,ES
405510,98994952,9899495,2,F,NaN,20240927,20140214,20240927,EXP,NaN,...,NaN,M,Y,NaN,NaN,20240927,NaN,HP,IT,IT
405511,99199918,9919991,8,F,20131203.0,20240822,20140224,20240903,EXP,NaN,...,A,F,Y,55.4,KG,20240903,NaN,CN,GB,GB
405512,99571342,9957134,2,F,20130525.0,20240726,20140304,20240805,EXP,NaN,...,NaN,M,Y,NaN,NaN,20240803,NaN,CN,US,US

In [4]:
#Selecting only the necessary columns
demo_df_2 = demo_df[['primaryid', 'caseid', 'i_f_code', 'age', 'age_cod', 'age_grp', 'sex', 'wt', 'wt_cod', 'init_fda_dt', 'fda_dt', 'reporter_country', 'occr_country']]
demo_df_2

,primaryid,caseid,i_f_code,age,age_cod,age_grp,sex,wt,wt_cod,init_fda_dt,fda_dt,reporter_country,occr_country
0,100138392,10013839,F,37.0,YR,NaN,M,NaN,NaN,20140316,20240726,FI,FI
1,1002310548,10023105,F,66.0,YR,E,F,NaN,NaN,20140320,20240715,CA,CA
2,100313066,10031306,F,58.0,YR,NaN,F,53.0,KG,20140324,20240802,JP,JP
3,100445154,10044515,F,55.0,YR,NaN,F,110.0,KG,20140328,20240922,IT,IT
4,100635983,10063598,F,64.0,YR,NaN,M,89.0,KG,20140407,20240725,GB,GB
...,...,...,...,...,...,...,...,...,...,...,...,...,...
405508,989327138,9893271,F,35.0,YR,A,F,74.0,KG,20140213,20240730,CA,CA
405509,98974507,9897450,F,64.0,YR,A,M,72.0,KG,20140214,20240919,ES,ES
405510,98994952,9899495,F,72.0,YR,NaN,M,NaN,NaN,20140214,20240927,IT,IT
405511,99199918,9919991,F,60.0,YR,A,F,55.4,KG,20140224,20240903,GB,GB
405512,99571342,9957134,F,20.0,YR,NaN,M,NaN,NaN,20140304,20240805,US,US

In [11]:
#Selecting only the pediatric population
age_grps = ['N', 'I', 'C', 'T']

demo_pedi_raw = demo_df_2[(demo_df_2['age_grp'].isin(age_grps)) | ((demo_df_2['age_grp'].isna()) & (demo_df_2['age']<19))]
demo_pedi_raw.head()

,primaryid,caseid,i_f_code,age,age_cod,age_grp,sex,wt,wt_cod,init_fda_dt,fda_dt,reporter_country,occr_country
27,102763263,10276326,F,10.0,YR,C,M,NaN,NaN,20140703,20240825,US,US
30,102857464,10285746,F,4.0,YR,C,M,67.200,KG,20140709,20240916,US,US
38,104473652,10447365,F,17.0,YR,T,M,58.968,KG,20140911,20240814,US,US
39,104475582,10447558,F,3.0,MON,I,F,NaN,NaN,20140911,20240814,US,US
43,104802623,10480262,F,10.0,YR,NaN,F,NaN,NaN,20140929,20240903,US,US

In [12]:
len(demo_pedi_raw)

24676

In [13]:
#Missing value counts and propotions
demo_pedi_raw.isna().sum()

primaryid               0
caseid                  0
i_f_code                0
age                  2989
age_cod              2989
age_grp             13747
sex                  1856
wt                  18733
wt_cod              18733
init_fda_dt             0
fda_dt                  0
reporter_country        0
occr_country          728
dtype: int64

In [29]:
#There are no any age values that misses age code that were selected from the age (ones without age grp)
demo_pedi_raw[(demo_pedi_raw['age'].isna() == False) & (demo_pedi_raw['age_cod'].isna() == True) & (demo_pedi_raw['age_grp'].isna() == True)]

Empty DataFrame
Columns: [primaryid, caseid, i_f_code, age, age_cod, age_grp, sex, wt, wt_cod, init_fda_dt, fda_dt, reporter_country, occr_country]
Index: []

In [30]:
#There are no any age values without age codes from the ones that were selected from the age groups
demo_pedi_raw[(demo_pedi_raw['age'].isna() == False) & (demo_pedi_raw['age_cod'].isna() == True) & (demo_pedi_raw['age_grp'].isna() == False)]

Empty DataFrame
Columns: [primaryid, caseid, i_f_code, age, age_cod, age_grp, sex, wt, wt_cod, init_fda_dt, fda_dt, reporter_country, occr_country]
Index: []

This means that all the age values have an age code

Now we can see the prpotions of age values and remove all that are smaller in values which gets not benefitted by being in an imbalanced dataset

In [36]:
#It's important to disregard age values that are higher than 18
demo_pedi_raw[((demo_pedi_raw['age'] > 18) & (demo_pedi_raw['age_cod'].isna()==True)) | ((demo_pedi_raw['age']>18) & (demo_pedi_raw['age_grp']=='YR'))]

Empty DataFrame
Columns: [primaryid, caseid, i_f_code, age, age_cod, age_grp, sex, wt, wt_cod, init_fda_dt, fda_dt, reporter_country, occr_country]
Index: []

In [33]:
demo_pedi_raw['age_cod'].value_counts()

age_cod
YR     18241
DEC     1965
MON      999
DY       335
WK       136
HR        11
Name: count, dtype: int64

In [34]:
(demo_pedi_raw['age_cod'].value_counts() / len(demo_pedi_raw)) * 100

age_cod
YR     73.922030
DEC     7.963203
MON     4.048468
DY      1.357594
WK      0.551143
HR      0.044578
Name: count, dtype: float64

Keep all the values. But convert them to years and use min-max scaling so that the small values won't be ignored when model is trained.

Also, add a custom age group category for binning for rule mining

Also, apply min-max scaler on the ages because the model predictions are happened from that

In [ ]:
#A function to convert months into years
def convertMt_Yr(df):
  if df['age_cod'] == 'MON':
    conv= round(df['age'] / 12,2)
    return conv
  elif df['age_cod'] == 'WK':
    conv = round(df['age'] / )