In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
#First extract the pids of the demographics that we filtered out
demo_pid_df = pd.read_csv('C:\\Users\\USER\\Desktop\\FYP\\fyp-sandbox-2\\Data\\CLEAN_DATA/demographics.csv')
demo_pid_df

,primaryid,caseid,i_f_code,age_yrs,age_bin,sex,Origin_country,wt_kg,init_fda_dt,fda_dt
0,186903752,18690375,F,10.00,Child,M,US,47.654523,20210101,20210111
1,186903891,18690389,I,15.00,Teenager,M,CN,62.537509,20210101,20210101
2,186904301,18690430,I,15.00,Teenager,F,US,58.717585,20210101,20210101
3,186905521,18690552,I,0.17,Infant,M,IE,34.982396,20210101,20210101
4,186905571,18690557,I,18.00,Teenager,M,US,62.482534,20210101,20210101
...,...,...,...,...,...,...,...,...,...,...
184045,247955131,24795513,I,16.00,Teenager,M,US,65.000000,20241231,20241231
184046,247988941,24798894,I,12.00,Child,F,US,41.730000,20241231,20241231
184047,247993241,24799324,I,16.00,Teenager,F,US,78.930000,20241231,20241231
184048,247996651,24799665,I,0.17,Infant,M,US,4.950000,20241231,20241231
184049,247997801,24799780,I,0.58,Infant,M,US,9.450000,20241231,20241231

In [3]:
demo_pids = demo_pid_df['primaryid']
len(demo_pids)

184050

## Drugs Data

In [4]:
#Importing the drugs entity
drug_raw = pd.read_csv('C:\\Users\\USER\\Desktop\\FYP\\fyp-sandbox-2\\Data\\RAW_DATA\\DRUGS/DRUG24Q4.txt', sep='$')
drug_raw

C:\Users\USER\AppData\Local\Temp\ipykernel_14416\1880806406.py:2: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  drug_raw = pd.read_csv('C:\\Users\\USER\\Desktop\\FYP\\fyp-sandbox-2\\Data\\RAW_DATA\\DRUGS/DRUG24Q4.txt', sep='$')

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
0,100100247,10010024,1,PS,ADALIMUMAB,ADALIMUMAB,1,Subcutaneous,NaN,NaN,NaN,Y,NaN,Not Available,NaN,125057.0,40.0,MG,NaN,QOW
1,100100247,10010024,2,SS,ADALIMUMAB,ADALIMUMAB,1,NaN,NaN,NaN,NaN,Y,NaN,NaN,NaN,125057.0,NaN,NaN,NaN,NaN
2,100100247,10010024,3,SS,CYCLOSPORINE,CYCLOSPORINE,1,Unknown,NaN,NaN,NaN,D,NaN,Not Available,NaN,65003.0,NaN,NaN,NaN,NaN
3,100100247,10010024,4,SS,REMICADE,INFLIXIMAB,1,Intravenous (not otherwise specified),6 infusions at 8 weeks interval,NaN,NaN,Y,NaN,Not Available,NaN,NaN,NaN,NaN,NaN,NaN
4,100100247,10010024,5,SS,ETANERCEPT,ETANERCEPT,1,Subcutaneous,NaN,NaN,NaN,Y,NaN,Not Available,NaN,NaN,100.0,MG,NaN,/WK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2030933,99696784,9969678,12,SS,DAPTOMYCIN,DAPTOMYCIN,1,Unknown,"500 mg, Daily",NaN,NaN,Y,NaN,NaN,NaN,NaN,500.0,MG,NaN,NaN
2030934,99696784,9969678,13,SS,PANTOPRAZOLE SODIUM I.V.,PANTOPRAZOLE SODIUM,1,Unknown,"40 mg, UNK",NaN,NaN,U,U,unk,NaN,NaN,40.0,MG,Injection,NaN
2030935,99696784,9969678,14,C,ACETAMINOPHEN\CODEINE PHOSPHATE,ACETAMINOPHEN\CODEINE PHOSPHATE,1,Unknown,"500/30 mg, daily",NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2030936,99696784,9969678,15,C,METHYLPREDNISOLONE,METHYLPREDNISOLONE,1,Unknown,"80 mg, bid",NaN,NaN,Y,NaN,NaN,NaN,NaN,80.0,MG,NaN,Q12H
2030937,99696784,9969678,16,C,METHYLPREDNISOLONE,METHYLPREDNISOLONE,1,Unknown,"12 mg, UNK ()",NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#selecting cases that matches the primary ids
drugs_df = drug_raw[drug_raw['primaryid'].isin(demo_pids)]
drugs_df

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
103151,186928283,18692828,1,PS,EVRYSDI,RISDIPLAM,1,Other,via gastric tube,NaN,NaN,Y,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,QD
103152,186928283,18692828,2,SS,EVRYSDI,RISDIPLAM,1,Other,via G-Tube,NaN,NaN,Y,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN
103511,1870365591,18703655,1,PS,IDURSULFASE,IDURSULFASE,1,Intravenous use,"12 milligram, 1/week",NaN,NaN,NaN,U,NaN,NaN,125151.0,12.0,MG,Concentrate for solution for infusion,/WK
103512,1870365591,18703655,1,PS,IDURSULFASE,IDURSULFASE,1,Intravenous use,"15 milligram, qd",NaN,NaN,NaN,U,NaN,NaN,125151.0,15.0,MG,Concentrate for solution for infusion,QD
103513,1870365591,18703655,1,PS,IDURSULFASE,IDURSULFASE,1,Intravenous use,"UNK UNK, 1/week",NaN,NaN,NaN,U,NaN,NaN,125151.0,NaN,NaN,Concentrate for solution for infusion,/WK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028757,247997801,24799780,1,PS,BEYFORTUS,NIRSEVIMAB-ALIP,1,Intramuscular,1 ml once intramuscular ?,NaN,NaN,D,D,AZ240068,NaN,NaN,1.0,ML,NaN,999
2028758,247997801,24799780,2,SS,PENTACEL,DIPHTHERIA AND TETANUS TOXOIDS AND ACELLULAR P...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028759,247997801,24799780,3,SS,PREVNAR 20,PNEUMOCOCCAL 20-VALENT CONJUGATE VACCINE,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028760,247997801,24799780,4,SS,HUMAN ROTAVIRUS A,HUMAN ROTAVIRUS A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2028761,247997801,24799780,5,SS,INFLUENZA VIRUS VACCINE,INFLUENZA VIRUS VACCINE,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
demo_pid_df[demo_pid_df['fda_dt'] >= 20241001]

,primaryid,caseid,i_f_code,age_yrs,age_bin,sex,Origin_country,wt_kg,init_fda_dt,fda_dt
248,187056213,18705621,F,13.00,Teenager,M,ES,58.947594,20210106,20241107
264,187063533,18706353,F,7.00,Child,F,GB,46.281392,20210106,20241218
1127,187408377,18740837,F,14.00,Teenager,M,DE,57.581210,20210114,20241210
1403,187577094,18757709,F,9.00,Child,M,ES,44.721524,20210119,20241122
2057,1878561911,18785619,F,13.00,Teenager,M,US,60.882321,20210125,20241126
...,...,...,...,...,...,...,...,...,...,...
184045,247955131,24795513,I,16.00,Teenager,M,US,65.000000,20241231,20241231
184046,247988941,24798894,I,12.00,Child,F,US,41.730000,20241231,20241231
184047,247993241,24799324,I,16.00,Teenager,F,US,78.930000,20241231,20241231
184048,247996651,24799665,I,0.17,Infant,M,US,4.950000,20241231,20241231
184049,247997801,24799780,I,0.58,Infant,M,US,9.450000,20241231,20241231

In [12]:
drugs_df.isna().sum()

primaryid            0
caseid               0
drug_seq             0
role_cod             0
drugname             0
prod_ai            763
val_vbm              0
route            20484
dose_vbm         15198
cum_dose_chr     60965
cum_dose_unit    60965
dechal           26221
rechal           56800
lot_num          46574
exp_dt           62279
nda_num          34716
dose_amt         32940
dose_unit        32940
dose_form        27725
dose_freq        44625
dtype: int64

In [ ]:
na_prod_ai = drugs_df[drugs_df['prod_ai'].isna()==True]['drugname']
na_prod_ai

114755                                      HIDERAX
124347         ENALAPRIL/HYDROCHLOROTHIAZIDE 2CARE4
124350                                          Lmx
130809                 DOXORUBICIN HYDROCHLORIDE NK
134863                                        Zydol
                             ...
2023314    adapalene-benzoyl peroxide 0.1-2.5 % gel
2023315                  ketoconazole 2 % shampoo,
2023316                      CLINDAMYCIN 1 A PHARMA
2023317        Aerochamber Max with Flow-VU inhaler
2023318                triamcinolone 0.025 % cream
Name: drugname, Length: 763, dtype: object

In [17]:
na_prod_ai = na_prod_ai.unique()

In [18]:
na_prod_ai

array(['HIDERAX', 'ENALAPRIL/HYDROCHLOROTHIAZIDE 2CARE4', 'Lmx',
       'DOXORUBICIN HYDROCHLORIDE NK', 'Zydol', 'SALACTOL', 'D1000',
       'Risek', 'Cal one D forte', 'SERT', 'Marzulene es', 'LOPEMIN',
       'ENORAS', 'PLEAMIN P', 'ASELEND', 'Kalinor', 'TOCOFERSOLAN',
       'ARGENPAL', 'Paidocort', 'IMMUNGLOBULIN',
       'FEXOFENADINE [FEXOFENADINE HYDROCHLORIDE]', 'PORTIA 21',
       'IMMUNE GLOBULIN', 'TRIAMCINOLON [TRIAMCINOLONE ACETONIDE]',
       'Cortiment', 'Salofalk', 'Fenadin',
       'Intravenous potassium chloride', 'ACIDOPHILUS/PECTIN', 'Maltofer',
       'LC PLUS', 'LOPERMIDE', 'POTASSIUM CITRATE CITRIC ACID', 'RECON',
       'Uralyt u', 'HEPARINOID', 'CALCIUM+ VITAMIN D', 'ELNEOPA NF NO.1',
       'SOLITA-T NO.2', 'METHYLPREDNISOLONE;OBINUTUZUMAB',
       'ANAKINRA RECOMBINANT', 'Maxim', 'Godex',
       'POTASSIUM MONOPHOSPHATE', 'MELATOBEL', 'Mcal d1000', 'PROBACLAC',
       'megamox', 'Allergy relief', 'PROBIOTIC COMPLEX', 'RINDERON',
       'SODIUM PHOSPHATE DIBASIC;SODIUM PHOSPHATE MONOBASIC (ANHYDROUS)',
       'MINERIC 5', 'INCREMIN', 'COQ', 'PN-TWIN NO. 2', 'AZUNOL',
       'SOLACET D', 'CIZANARINE N', 'ELEJECT',
       'METHYLROSANILINIUM CHLORIDE', 'Liquid calcium',
       'CRIZANLIZUMAB TMCA', 'SARS-COV-2 VACCINE', 'VITAMIN D-400',
       'DEOXYRIBONUCLEASE, NATURAL', 'Covid-19 vaccine', 'RESCUE',
       'ENEMAX', 'Reactine', 'DAYTIME COUGH + COLD', 'SOLU CORTEF MIX O',
       'BETAMETH DIPROPIONATE', 'Enox', 'KIDS MULTI GUMMIES', 'Dorsiflex',
       'FISIOGEN FERRO FORTE', 'Prodefen plus', 'COVID-19 VACCINE',
       'ADVIL JUNIOR STRENGTH', 'URSOCOL', 'DIPHENDRAMINE EXPECTORANT',
       'GENTAX', 'COMIRNATY', 'DIPHTHERIA, TETANUS, POLIO VACCINE',
       'BETNEVATE', 'MYSER [DIFLUPREDNATE]', 'PREDNISOLONE VALEROACETATE',
       'MOIZERTO', 'Hep lock', 'Phosphorus;Potassium;Sodium',
       'SALBUTAMOL SYRUP', 'MELATONIN LIQUID HORIZON',
       'LOPEMIN FOR CHILDREN', 'Ferroglobin', 'VIDROP',
       'SALBUTAMOL VIATRIS', 'IPRATROPIUM VIATRIS ADULTS',
       'Immunoglobulin', 'VIGANTOL', 'Panto', 'NANO', 'ALLERTEK',
       'B. BRAUN PARACETAMOL', 'Methylpredni',
       'POLYVISOL [ASCORBIC ACID;ERGOCALCIFEROL;NICOTINAMIDE;RETINOL PALMITATE',
       'ERYTHROMYCIN ETHYL', 'TRIMETROPINA SULFAMETOXAZOL', 'LIPISTART',
       'ARVECAP', 'LOMUSTINE;TEMOZOLOMIDE',
       'AMOXCLAV [AMOXICILLIN TRIHYDRATE;CLAVULANATE POTASSIUM]',
       'NGENLA [SOMATROGON]', 'CULTURELLE PROBIOTICS',
       'RISPERDAL, L-CARNITINE', 'PERIFLEX ADVANCE 35 G 369 POWDER',
       'GLOBULIN', 'B12', 'Vigantol', 'ECHINACEA HERB [ECHINACEA SPP.]',
       'MUCINEX CHILDREN^S FREEFROM COUGH + MUCUS',
       'epinephrine jr auto inj 2pk', 'alphanate inj', 'Flomox',
       'Mouse nerve growth factor', 'HEP A IN VAC', 'HEP B VAX',
       'LMX 4 PLUS', 'WIDECILLIN [AMOXICILLIN TRIHYDRATE]', 'Fortinil',
       'BOSWELLIA EXTRAKT 400MG', 'Dormicum', 'Laxans', 'MUCOCLEAR',
       'DEKA', 'WELLKID CALCIUM', 'DEKAS ESSENTIAL', 'Duoderm', 'ENEVO',
       'GLOBULIN V', 'TEAR DROPS', 'KLATEX', 'Kidcal', 'TUMS CHEWIES',
       'DEP TESTOSTERONE', 'CALCIUM/VITAMIN D3/MAGNESIUM',
       'MUCOSAL [ACETYLCYSTEINE]',
       'Brompheniramine maleate, pseudoephedrine hcl, dextromethorphan hydrobr',
       'FLINTSTONES OMEGA 3 DHA', 'Ribavirin spray', 'Vitamin AD drops',
       'Chloral hydrate syrup', 'Ibuprofen Suspension Solution',
       'Ibuprofen suppository', 'Anti-cold granules',
       'Open Throat Sword Spray', 'Cefaclor dry suspension',
       'Cefoperazone sodium sulbactam sodium (2:1) injection', 'DUOCAL',
       'SKYTROFA [LONAPEGSOMATROPIN]', 'PAEDIATRIC SERAVIT',
       'MUCINEX COLD + FLU', 'SHIMOTSUTO', 'KANAVIT',
       'PEDIASURE PEPTIDE 1.5 CAL', 'Calcium + Vitamin D3 + K2',
       'LEVETIRACETAM WOCKHARDT', 'CULTURELLE KIDS PACKETS',
       'LEUPRORELINA [LEUPRORELIN ACETATE]', 'HIBOR', 'Salvacolina',
       'BENADRYL ALLERGY + COLD', 'MINT LEUCOVORIN',
       'NANOVM 9 TO 18 YEARS', 'CUVPOSA [GLYCOPYRRONIUM]',
       'MULTIVITAMINES WITH IRON [ASCORBIC ACID;CYANOCOBALAMIN;ERGOCALCIFEROL;',
       'DIURIL [CHLOROTHIAZIDE SODIUM]', 'ORA [LORAZEPAM]', 'Spasfon',
       'FLINTSTONES COMPLETE VITAMIN', 'XYNTHA SOLOF INJ',
       'LEVETIRACETAM AFT', 'Triamcinolon', 'FLUCORT', 'Mellozzan',
       'Nolotil', 'OMEPRAZOLE STADA', 'CHILDREN^S TYLENOL COLD + COUGH',
       'MULTIVITAMIN GUMMY', 'DANDELIN TEA',
       'EASY GLIDE LUER LOCK SYRINGE', 'DEPOTESTOSTERONE CYPIONATE',
       'ZOFRAN-ODT', 'FLINTSTONES MULTIVITAMIN', 'TURMERIC CUMIN GINGER',
       'FLINTSTONES WITH OMEGA-3 DHA', 'EXONDYS',
       'IMMUNE C PLUS ZINC PLUS VITAMIN D',
       'SEA MOSS BLADDER WRACK AND BURDOCK ROOT', 'MELATONIN GUMMY',
       'EXODYS 51', 'AMONDYS', 'FLINTSTONE VITAMINS WITH IRON',
       'SEA MOSS', 'BURDOCK ROOT', 'VYONDYS', 'KID^S MULTIVITAMIN GUMMY',
       'PROBIOTIC KID', 'MICAFUNGIN SODIUM FOR INJECTION SINGLE USE',
       'PENTAMIDINE ISETHIONATE INJ 300MG/VIAL BP',
       'zinc menthol lozenges', 'vitamin d3 chewable',
       'Copper supplement', 'unknown probiotics, chewable',
       'immunoglobin', 'UNICTAM [AMPICILLIN SODIUM;SULBACTAM SODIUM]',
       'CIPROFLAXINA HC LAZAR', 'LORATADINE TEVA', 'Hiya multivitamin',
       'ACCUTANE', 'ACYCLOVIR STADA', 'CROMOGLYCATE DISODIUM', 'Glycyron',
       'MADELEINE', 'ZINC ACETATE DIHYDRATE', 'LEVOCARNITINE FF',
       'periflex junior', 'DORNAVAC',
       'Pediatric Compound Amino Acid Injection (18AA-I)', 'MODULIN',
       'TRANEXAMSAURE EBERTH', 'Prenatal Vit-Fe Fumarate-FA',
       'GLUCOSE 20% BRAUN', 'hypersal 7%', 'LANSOPRAZOLE',
       'LEVOTHYROXINE', 'PHENOBARBITAL', 'PULMICORT', 'VALIUM',
       'immunoglobulin', 'EAR DROPS RX', 'MELLOZZAN',
       'Antiobiotic eye infection', 'Eye Ointment stye ',
       'Tranexamsaure eberth', 'BENADRYL ALLERGY RELIEF',
       'advate injection', 'novoseven rt mp (1000 u)', 'Hydroxyzinum vp',
       'Old Spice ^Scent of Cedarwood^ bodywash',
       'Dove Sensitive Skin Hypoallergenic bodywash',
       'Tacrolimus Ointment (0.03%)', 'PROTHROMBINKOMPLEX-KONZENTRAT',
       'CARBOHYDRATES NOS;FATS NOS;LEVOCARNITINE;MINERALS NOS;PROTEINS NOS;TAU',
       'KETOCONAZOLE EG', 'Glutaferro',
       'TRANEXAMSAURE EBERTH (TRANEXAMIC ACID)',
       'MULTIVITAMIN [ASCORBIC ACID;COLECALCIFEROL;DEXPANTHENOL;NICOTINAMIDE;P',
       'Fresh frozen plasma and granulocyte colony-stimulating factor (G-CSF)',
       'High-dose vasoactive drugs and multiple transfusions of ?platelets',
       'EMICIZUMAB KXWH', 'HAEMOCTIN', 'DORMICUM', 'TANNO HERMAL',
       'POXCLIN COOLMOUSSE', 'BIOFLORIN', 'GASTROGEL (MOROCCO)',
       'AMOXIL FORTE', 'DESOMEDIN', 'NASIVINE', 'EFFEXIN', 'ACETALGIN',
       'ALMAGEL [ALGELDRATE;MAGNESIUM HYDROXIDE]',
       'SKY CELLFLU QUADRIVALENT', 'FUMARATE FERREUX TM',
       'BECLAZONE EASI-BREATHE', 'vitamin C tablets',
       'HEPARIN L/F SYR (3ML/SYR)',
       'Complete Formulation Multivitamin +D3000',
       'Sodium chloride 7% nebulized solution',
       'ALLERGY NASAL DECONGESTANT', 'Feroglobin', 'ALFLOREX', 'ZINCASA',
       'KALIUM GLUCONICUM', 'Ferrum Lek',
       'SULFAMETHOXAZOLE AND RIMETHOPRIM', 'CERAVE PSORIASIS',
       'EYE OINTMENT (UNK INGREDIENTS)', 'RINGER AGUETTANT',
       'MONTELUCASTE SODICO', 'Budesonide-formoterol 160/4.5',
       'Fluticasone-Salmeterol 115/21', 'ipratropium 17 mcg inhaler',
       'DAILY VITE [ASCORBIC ACID;CALCIUM PANTOTHENATE;COLECALCIFEROL;CYANOCOB',
       'EPINEPHRINE [EPINEPHRINE HYDROCHLORIDE]', 'Pentasa(Mesalazine)',
       'GUANFACINE', 'Oxinorm', 'HYPEROL', 'CIPRODEX (UNITED STATES)',
       'ELEMENTAL ZINC', 'MIRANAX', 'HYPERTONIC SOLUTIONS', 'HEMOSIN-K',
       'SECNIDAL', 'VITAMIN A;VITAMIN C;VITAMIN D', 'ALBUTAMOL',
       'DEKASOL', 'GRANULOCYTE MACROPHAGE COLONY STIM', 'FERODAN',
       'SALTSTICK', 'GINGER ROOT [ZINGIBER OFFICINALE RHIZOME]',
       'KATE FARMS STANDARD 1.0', 'HYDROCORT [HYDROCORTISONE]',
       'HYDROCORTISONE [HYDROCORTISONE VALERATE]', 'Melatin',
       'GENE THERAPY', 'Cal one d', 'EVASTIX', 'SALFLUMIX EASYHALER',
       'ADVIL TABS', 'Beclazone', 'IRON/VITAMINS NOS', 'Morfin',
       'Ondansetron ebb', 'PROPRANOLOL SOL', 'VITAMIN D ', 'FK',
       'CITRIC ACID;SODIUM CITRATE',
       'GRANULOCYTE COLONY STIMULATING FACT', 'BECLAZONE',
       'ONDANSETRON STADA', 'Polyethylene Glycol Electrolytes',
       'ACETYLCYSTEINE [ACETYLCYSTEINE SODIUM]',
       'Ceftazidime / Avibactam', 'Pertussin',
       'aminocaproic acid oral solution', 'Fenoximetilpenicilina',
       'Prevnar-20', 'Rota Teq', 'Nirsevimnab-Alip', 'Tandem Tslim X2',
       'Dexcom G7', 'MAGISTRAL [TIABENDAZOLE]', 'VITAMIN D;VITAMIN E',
       'fenoximetilpenicilina', 'nitazoxanide 500mg tablets',
       'ferrous sulfate 325mg tablets', 'Ketonal', 'Biotine', 'BEFLAVINE',
       'Acetozolamide', 'SENNA LEAVES [SENNA SPP.]', 'Clemastina',
       'sodium-chloride (normal saline)', 'Bepanthen',
       'TRANEXAMINEZUUR SANDOZ', 'Apcion', 'N-acetylcysteine (SYN)',
       'EQUATE MULTIVITAMIN GUMMIE', 'ALPROLIX INJ', 'PRENI',
       'INSULIN OLAR SOL 100U/ML', 'MULTI-VITAMN TAB', 'SODIUM CHLORIDE',
       'BLUNT FILTER ', 'EPIDIOLEX ORAL SOLN', 'HEMLIBRA SDV ',
       'JEVITY 1.2 CAL', 'NORETHIN',
       'CHILDREN^S CETIRIZINE HYDROCHLORIDE', 'AQUAPHOR ANTIBIOTIC',
       'CHILDREN^S BENADRYL ALLERGY + SINUS',
       'PERTUSSIN [POTASSIUM BROMIDE;THYMUS SERPYLLUM]', 'DEPAKOTE',
       'RISPERIDONE', 'Toplexil', 'Cannabidiol glostrup', 'VITAMIN A D',
       'OXCARBAZEPINE', 'Vitamin c ', 'multivitamin chew ', 'TYLENOL',
       'Dimitap', 'Clobestasol ointment', 'Triamcinolone nasal spray',
       'ATIVAN TAB 1MG ', 'LORATADINE AMEL', 'NSAID N',
       'FOXIN [OFLOXACIN]', 'ZARBEE COUGH MEDICINE',
       'CHILDREN^S MULTIVITAMIN', 'black seed oil',
       'prebiotic/probiotic capsule', 'DANDELION ROOT', 'HIDROTISONA',
       'Octenisan', 'Dinutuximab-beta', 'MIRALAX', 'Probiotics ',
       'FIBERS', 'MONTELUKAST', 'Guanfacine ER 4 mg', 'Focalin XR 20 mg',
       'ENFAMIL REGULINE', 'ELECARE FOR INFANTS',
       'AZITHROMYCIN SUS 200/5ML', 'EPINEPHRINE INJ 0.15MG',
       'FLOVENT HFA AER 44MCG',
       'MULTIVITAMIN [ASCORBIC ACID;COLECALCIFEROL;NICOTINAMIDE;PYRIDOXINE HYD',
       'VITAMIN D3 GUMMIES', 'MELATONIN KIDS', 'CHILDREN^S LORATADINE',
       'ROBITUSSIN HONEY COUGH AND CHEST DM', 'HPA LANOLIN', 'D-VI-SOL',
       'HYLAND^S COLD AND COUGH',
       'ZARBEE^S NATURALS COUGH SYRUP DARK HONEY', 'KIDS MULTIVITAMINS',
       'KIDS PROBIOTIC', 'ADVANCED PROBIOTIC', 'QC VITAMIN D3',
       'SV MAGNESIUM', 'EDG/i506', 'MULTIVITAMIN KIDS', 'NAC',
       'CHILDREN PEPTO', 'Serum saline', 'Histamine Chloride',
       'EPIPEN [EPINEPHRINE HYDROCHLORIDE]', 'IRON PROTEINSUCCINYLATE',
       'OCTENISAN CLEANING',
       'PEPTAC [CALCIUM CARBONATE;SODIUM ALGINATE;SODIUM BICARBONATE]',
       'Daforin (fluoxetine hydrochloride)',
       'PIPERACILLIN ANDTAZOBACTAM FOR INJECTION', 'Argi u',
       'Immuneglobulin', 'HISTEX PD [TRIPROLIDINE HYDROCHLORIDE]',
       'Fat-soluble Vitamin for Injection (I)', 'BENZOYLMETRONIDAZOLE',
       'TARCEFOKSYM', 'Multivitamin up+up', 'SPASFON', 'Beet root',
       'BETA ALANINE', 'EASYHALER', 'CHILDREN^S ALL DAY ALLERGY',
       'CONCERTO', 'EUCERIN ECZEMA RELIEF', 'HYDROCORTISONE IVAL',
       'HYDROCORTISONE [HYDROCORTISONE HYDROGEN SUCCINATE]',
       'GLYCYRRHIZINATE MONOAMMONIUM; GLYCINE; DL-METHIONINE', 'Amicasin',
       'THIOACETAZONE', 'Unitro', 'Utroves', 'Mirabegrona',
       'REUTERINA DAILY', 'CEFASYN', 'TOBRAMYCIN', 'Sertra!ine',
       'cymbicort', 'Olly kids multi', 'THYROX',
       'steroid / anti fungal creams for skin', 'EUNOCTIN',
       'TALOXA [FELBAMATE]', 'Sultiamine', 'FLUTICASON HFA', 'AMLOPEN',
       'DIUREN [HYDROCHLOROTHIAZIDE]', 'BAN XIA [PINELLIA TERNATA TUBER]',
       'CIANOCOBALAMINA', 'Protovit', 'Hydroxyzine 10 mg',
       'URSODEOXYCHOLIC AC', 'OLOPATADINA [OLOPATADINE]', 'METHYLPREDNI',
       'BIOTINE', 'B amphotericin', 'Tetrahydro-cannabinol',
       'Vitamin D HPI', 'CULTURELLE HEALTH and WELLNESS PROBIOTIC',
       'MIRALAX 3350 NF', 'BROMFENAC;PREDNISOLONE', 'BLUNT FILTER NEEDL',
       'Florababy', 'POLY-VI-SOL [VITAMINS NOS]', 'NOLOTIL',
       'SIBILLA DIARIO', 'BLUNT FILER NEEDL 18GX1-1/2',
       'COVID-19 vaccine', 'MULTIVITAMIN GUMMY BEARS', 'PROBIOTIC JUNIOR',
       'Dornase alpha', 'FLUTICASON [FLUTICASONE]', 'Topical Mometasone',
       'Nasal', 'Rabbit anti-thymocyte globulin (R-ATG)',
       'SLENYTO 5 mg, comprim? ? lib?ration prolong?e', 'SALOMOL',
       'WHOLE GERMINATES', 'SENOVITAL', 'REVANIN', 'bronchospasm',
       'asthma', 'anaphylaxis', 'NOVOSEVEN RT MP',
       'EPINEPI-RINE INJ (1MLX10)', 'METRONIDAZOL BENZOATE',
       'Sulthiamine', 'Whole germinates', 'omni pod 5', 'dexcom 6 ',
       'Albuterol inhaler 90 mcg as needed',
       'Budesonide-formoterol 80 mcg-4.5 mcg 2 puffs BID',
       'deflazacort 22.75 mg/mL  1.3 mL daily',
       'famotidine 40 mg/5 mL 5 mLBID',
       'diphenhydramine 12.5 mg TID before infusion',
       'acetaminophen prior to infusion',
       'multivitamin with minerals daily', 'ondansetron 4 mg TID',
       'polyethylene glycol 3350 17 g daily', 'BECLOMETHASONE INHALER',
       'DAVERCIN', 'EFFER K', 'LEVOCARNITIN', 'KETONE', 'Ospen',
       'POLY-VI-SOL [ASCORBIC ACID;COLECALCIFEROL;NICOTINAMIDE;RETINOL;RIBOFLA',
       'Diclofenac suppositories',
       'CALCIUM +D [CALCIUM CARBONATE;COLECALCIFEROL]', 'LUDENT FLUORIDE',
       'Chlorpheniramine Mealate', 'METHYLPHENIDAT 1 A PHARMA',
       'Asparaginase [lasparaginase]', 'BROM/PSE/DM',
       'FLONASE ALLERGY SPRAY', 'PULMICORT INH', 'Sertralne',
       'Women^s Iron supplements', 'Vitamin C supplements', 'TIRIZINE',
       'URSOMAX', 'TIGERASE', 'FLUNITRAZEPAM-B', 'Immune-globulin',
       'BETAMET [BETAMETHASONE SODIUM PHOSPHATE]', 'FLURANDRENOLONE',
       'HYDROCORTISONE ECZEMA RESCUE', 'ALOCANE EMERGENCY BURN GEL',
       'POLY VI SOL WITH IRON', 'Innofer',
       'MULTIVITAMIN [ASCORBIC ACID;CALCIUM PANTOTHENATE;CYANOCOBALAMIN;NICOTI',
       'CALCIUM WITH VIT D3 (CHOLECALCIFEROL)',
       'tacrolimus 0.1 % ointment', 'cetirizine 10 mg tablet, ',
       'Symbicort 80-4.5 mcg/actuation inhaler, ',
       'Retin-A 0.025 % cream, ', 'mometasone 0.1 % cream, ',
       'adapalene-benzoyl peroxide 0.1-2.5 % gel',
       'ketoconazole 2 % shampoo, ', 'CLINDAMYCIN 1 A PHARMA',
       'Aerochamber Max with Flow-VU inhaler',
       'triamcinolone 0.025 % cream '], dtype=object)

In [ ]:
drugs_df[drugs_df['drugname'].isin(na_prod_ai)]

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
103515,1870365591,18703655,2,C,RISPERIDONE,RISPERIDONE,1,Oral use,"5 milliliter, qd",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,ML,NaN,QD
104145,1872096917,18720969,9,C,RISPERIDONE,RISPERIDONE,1,Oral,UNK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114755,1894049627,18940496,2,C,HIDERAX,NaN,1,NaN,UNK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118864,1899265120,18992651,36,SS,MONTELUKAST,MONTELUKAST,1,Oral,"10 mg, qd (1 every 1 days)",NaN,NaN,Y,NaN,NaN,NaN,NaN,10.0,MG,NaN,QD
118867,1899265120,18992651,39,SS,PHENOBARBITAL,PHENOBARBITAL,1,Oral,"30 mg, bid (2 every 1 days)",NaN,NaN,Y,NaN,NaN,NaN,NaN,30.0,MG,NaN,BID
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023316,247939581,24793958,10,C,CLINDAMYCIN 1 A PHARMA,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023317,247939581,24793958,11,C,Aerochamber Max with Flow-VU inhaler,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023318,247939581,24793958,12,C,triamcinolone 0.025 % cream,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023544,247940681,24794068,1,PS,TYLENOL,ACETAMINOPHEN,1,Unknown,"2 dosage form, once a day",NaN,NaN,U,U,Unknown,NaN,19872.0,NaN,NaN,Unknown,QD
2023545,247940681,24794068,2,SS,TYLENOL,ACETAMINOPHEN,1,NaN,NaN,NaN,NaN,U,U,NaN,NaN,19872.0,NaN,NaN,NaN,NaN

In [22]:
drugs_df[(drugs_df['drugname'] == 'TYLENOL') & (drugs_df['prod_ai'].isna() == True)]

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
1393603,246078411,24607841,6,C,TYLENOL,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
len(drugs_df[drugs_df['drugname'].isin(na_prod_ai)]['drugname'].unique())

566

Can actually replace most of the missing prod_ai values from existing ones. 

Make a lookup table with unique prod_ai and drugnames. Use it to replace the missing values. Then the ones without prod_ai will be dismissed (from the case itself)

## Reactions Data

In [25]:
reactions_raw = pd.read_csv('C:\\Users\\USER\\Desktop\\FYP\\fyp-sandbox-2\\Data\\RAW_DATA\\REACTIONS/REAC24Q4.txt', sep='$')
reactions_raw

,primaryid,caseid,pt,drug_rec_act
0,100100247,10010024,Malignant melanoma stage I,NaN
1,100100247,10010024,Keratoacanthoma,NaN
2,100100247,10010024,Blood pressure increased,NaN
3,100100247,10010024,Keratoacanthoma,NaN
4,100100247,10010024,Hyperkeratosis,NaN
...,...,...,...,...
1472745,99310703,9931070,Liver transplant rejection,NaN
1472746,99310703,9931070,Post transplant lymphoproliferative disorder,NaN
1472747,99310743,9931074,Post transplant lymphoproliferative disorder,NaN
1472748,99696784,9969678,Drug reaction with eosinophilia and systemic s...,NaN
1472749,99696784,9969678,Toxic epidermal necrolysis,NaN

In [26]:
#Selecting reactions for our cases
reactions_df = reactions_raw[reactions_raw['primaryid'].isin(demo_pids)]
reactions_df

          primaryid    caseid                           pt drug_rec_act
67792     186928283  18692828                      Seizure          NaN
67968    1870365591  18703655              Fluid retention          NaN
67969    1870365591  18703655      Treatment noncompliance          NaN
67970    1870365591  18703655       Intestinal perforation          NaN
67971    1870365591  18703655         Abdominal discomfort          NaN
...             ...       ...                          ...          ...
1470637   247988941  24798894  Incorrect dose administered          NaN
1470684   247993241  24799324                    Influenza          NaN
1470777   247996651  24799665          Skin discolouration          NaN
1470789   247997801  24799780            Rash erythematous          NaN
1470790   247997801  24799780                 Rash papular          NaN

[62971 rows x 4 columns]

In [27]:
reactions_df.isna().sum()

primaryid           0
caseid              0
pt                  0
drug_rec_act    62899
dtype: int64

There are more than 1 reactions for some cases

## Outcome Data

In [28]:
outcome_raw = pd.read_csv('C:\\Users\\USER\\Desktop\\FYP\\fyp-sandbox-2\\Data\\RAW_DATA\\OUTCOMES/OUTC24Q4.txt', sep='$')
outcome_raw

         primaryid    caseid outc_cod
0        100100247  10010024       OT
1        100373859  10037385       DS
2        100373859  10037385       OT
3       1016611044  10166110       HO
4       1016611044  10166110       OT
...            ...       ...      ...
308955    99310683   9931068       OT
308956    99310703   9931070       DE
308957    99310703   9931070       OT
308958    99310743   9931074       DE
308959    99696784   9969678       OT

[308960 rows x 3 columns]

In [29]:
#Selecting the ones that matches our cases
outcome_df = outcome_raw[outcome_raw['primaryid'].isin(demo_pids)]
outcome_df

         primaryid    caseid outc_cod
7986     186928283  18692828       OT
8015    1870365591  18703655       OT
8016    1870365591  18703655       HO
8018     187056213  18705621       OT
8019     187056213  18705621       DE
...            ...       ...      ...
308442   247952521  24795252       DS
308542   247953881  24795388       OT
308592   247954711  24795471       HO
308670   247955631  24795563       OT
308681   247955801  24795580       OT

[10514 rows x 3 columns]

Apart from the DRUGS entity, the others can be just appended as they are